version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: docker-start-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - docker-start-network

  api:
    build: ./api
    container_name: docker-start-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=4200
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_URL=http://auth:4300
    depends_on:
      - api_db
    networks:
      - docker-start-network

  auth:
    build: ./auth
    container_name: docker-start-auth
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=4300
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:4200
    depends_on:
      - auth_db
    networks:
      - docker-start-network

  api_db:
    image: mongo:latest
    container_name: docker-start-api-db
    volumes:
      - mongodb_api:/data/api_db
    networks:
      - docker-start-network

  auth_db:
    image: mongo:latest
    container_name: docker-start-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - docker-start-network

  nginx:
    image: nginx:stable-alpine
    container_name: docker-start-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - docker-start-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  docker-start-network:
    driver: bridge
